WHERE {
	{
		SELECT DISTINCT ?obs ?phenomenonTime
		$GRAPHS_LIST$
	  	WHERE {
			?col	rdf:type/rdfs:subClassOf*	sosa:ObservationCollection;
					sosa:phenomenonTime/time:hasBeginning/time:inXSDDateTimeStamp|sosa:phenomenonTime/time:inXSDDateTimeStamp|sosa:phenomenonTime	?phenomenonTime;
				  	sosa:hasMember      		?obs.
            ?obs	rdf:type/rdfs:subClassOf*	sosa:Observation;
                    sosa:hasFeatureOfInterest   ?foi.
            BIND(REPLACE(STR(?foi), "^.*/([^/]*)$", "$1") AS ?foi_id)
            FILTER(?foi_id = "{id}")
		}
	 	$LIMIT_OFFSET$
	}
	?obs    sosa:resultTime     		?resultTime;
            sosa:hasSimpleResult        ?result.
	BIND(REPLACE(REPLACE(STRAFTER(STR(?obs), "observation/"), "/", "-"), "%20", "-") AS ?id)
    BIND(URI(CONCAT('{bare_request_url}(', ?id,')')) AS ?self_link)
    BIND(URI(CONCAT('{bare_request_url}(', ?id,')/Datastream')) AS ?datastream_link)
    BIND(URI(CONCAT('{bare_request_url}(', ?id,')/FeatureOfInterest')) AS ?feature_link)
}
$CODE_1$