WHERE {
    ?col    sosa:hasFeatureOfInterest   ?foi;
            sosa:hasMember      		?obs.
    ?obs    sosa:resultTime             ?time.
    ?foi    wgs84:lat                   ?raw_lat;
            wgs84:long                  ?raw_long.
    BIND(REPLACE(REPLACE(STRAFTER(STR(?obs), "observation/"), "/", "-"), "%20", "-") AS ?historical_locations_id)
    FILTER(?historical_locations_id = "{id}")
}
