WHERE {
    {
        SELECT DISTINCT ?id (MAX(?lat) AS ?lat) (MAX(?long) AS ?long)
        $GRAPHS_LIST$
        WHERE {
            ?foi    rdf:type/rdfs:subClassOf*   sosa:FeatureOfInterest;
                    geo:hasGeometry             ?geom.
            ?geom   geo:asWKT                   ?wkt.
            BIND(STRBEFORE(STRAFTER(STR(?wkt), "("), " ") AS ?lat)
            BIND(STRBEFORE(STRAFTER(STR(?wkt), " "), ")") AS ?long)
            BIND(CONCAT("lat=", ?lat, ":long=", ?long) AS ?id)
            FILTER(?id = "{id}")
        }
    }
    BIND(URI(CONCAT('{bare_request_url}')) AS ?self_link)
    BIND(CONCAT("Location with latitude=", ?lat, " and longitude=", ?long) AS ?description)
    BIND(CONCAT("Lat=", ?lat, " long=", ?long) AS ?name)
    BIND("application/vnd.geo+json" AS ?encodingType)
    BIND(URI(CONCAT('{bare_request_url}/Things')) AS ?things_link)
    BIND(URI(CONCAT('{bare_request_url}/HistoricalLocations')) AS ?historical_locations_link)
}
$CODE_0$