WHERE {
    {
        SELECT DISTINCT ?id (MAX(?lat) AS ?lat) (MAX(?long) AS ?long)
        $GRAPHS_LIST$
        WHERE {
            ?foi    rdf:type/rdfs:subClassOf*   sosa:FeatureOfInterest;
                    wgs84:lat                   ?raw_lat;
                    wgs84:long                  ?raw_long.
            BIND(REPLACE(?raw_lat , "[^0-9.]", "") AS ?lat)
            BIND(REPLACE(?raw_long, "[^0-9.]", "") AS ?long)
            BIND(REPLACE(STR(?foi), "^.*/([^/]*)$", "$1") AS ?id)
            FILTER(?id = "{id}")
        }
    }
    BIND(URI(CONCAT('{bare_request_url}')) AS ?self_link)
    BIND(CONCAT("Feature of interest: ", ?id, " with latitude=", ?lat, " and longitude=", ?long) AS ?description)
    BIND(CONCAT("FoI: ", ?id) AS ?name)
    BIND("application/vnd.geo+json" AS ?encodingType)
    BIND(URI(CONCAT('{bare_request_url}/Observations')) AS ?observations_link)
}
$CODE_32$