WHERE {
    ?col    sosa:observedProperty   ?obs_property;
            sosa:hasMember          ?obs.
    ?obs    sosa:madeBySensor       ?sensor;
            sosa:hasSimpleResult    ?r.
    BIND(REPLACE(STR(?sensor), "^.*/([^/]*)$", "$1") AS ?thing_id)
    FILTER(?thing_id = "{id}")
}
