WHERE {
    ?col    sosa:madeBySensor           ?sensor;
            sosa:hasMember      		?obs.
    ?obs    sosa:hasFeatureOfInterest   ?foi.
    ?foi    wgs84:lat                   ?raw_lat;
            wgs84:long                  ?raw_long.
    BIND(REPLACE(STR(?sensor), "^.*/([^/]*)$", "$1") AS ?thing_id)
    FILTER(?thing_id = "{id}")
}
