WHERE {
    ?col    rdf:type/rdfs:subClassOf*   sosa:ObservationCollection;
            sosa:hasFeatureOfInterest   ?foi;
            sosa:madeBySensor           ?sensor.
    ?foi    wgs84:lat                   ?raw_lat;
            wgs84:long                  ?raw_long.
    BIND(REPLACE(STR(?sensor), "^.*/([^/]*)$", "$1") AS ?thing_id)
    FILTER(?thing_id = "{id}")
}
