"""empty message

Revision ID: 4ee601c954b9
Revises:
Create Date: 2023-08-18 08:52:13.805537

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4ee601c954b9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pilots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("graphs", sa.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pilots_id"), "pilots", ["id"], unique=False)
    op.create_index(op.f("ix_pilots_name"), "pilots", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pilots_name"), table_name="pilots")
    op.drop_index(op.f("ix_pilots_id"), table_name="pilots")
    op.drop_table("pilots")
    # ### end Alembic commands ###
