"""empty message

Revision ID: 729c29e6721a
Revises: e68d3af8412e
Create Date: 2024-03-23 10:57:52.054990

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "729c29e6721a"
down_revision = "e68d3af8412e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pilots", sa.Column("cached_properties", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pilots", "cached_properties")
    # ### end Alembic commands ###
