"""empty message

Revision ID: e580ba4fcca4
Revises: 4ee601c954b9
Create Date: 2023-09-25 15:04:20.135314

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e580ba4fcca4"
down_revision = "4ee601c954b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pilots", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pilots", "description")
    # ### end Alembic commands ###
