"""empty message

Revision ID: e68d3af8412e
Revises: e580ba4fcca4
Create Date: 2023-12-09 20:47:59.658686

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e68d3af8412e"
down_revision = "e580ba4fcca4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pilots", sa.Column("custom_endpoint", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pilots", "custom_endpoint")
    # ### end Alembic commands ###
