WHERE {
    {
        SELECT DISTINCT ?sensor
        $GRAPHS_LIST$
        WHERE {
            ?col    sosa:madeBySensor       ?sensor;
                    sosa:hasMember          ?obs.
            ?obs    sosa:observedProperty   ?obs_property.
            BIND(REPLACE(STR(?sensor), ".*(#|/)", "") AS ?sensor_name)
            BIND(REPLACE(STR(?obs_property), ".*(#|/)", "") AS ?obs_property_name)
            BIND(CONCAT(?sensor_name, "-", ?obs_property_name) AS ?datastream_id)
            FILTER(?datastream_id = "{id}")
        }
    }
    ?sensor     rdfs:label  ?description.
    FILTER(lang(?description) = 'en' || lang(?description) = '')
    OPTIONAL {
        ?sensor rdf:type/rdfs:subClassOf*|dct:type   ?type1.
        FILTER(?type1 != sosa:Sensor)
    }
    BIND(COALESCE(?type1, sosa:Sensor) as ?type)
    BIND(REPLACE(STR(?sensor), "^.*/([^/]*)$", "$1") as ?id)
    BIND(URI(CONCAT('{bare_request_url}(', ?id,')')) AS ?self_link)
    BIND(STR(CONCAT(?type, " - ", ?id)) AS ?name)
    BIND(STR('application/json') AS ?encodingType)
    BIND(URI(CONCAT('{bare_request_url}(', ?id,')/Datastreams')) AS ?datastreams_link)
}
