WHERE {
	{
		SELECT DISTINCT ?id ?obs ?phenomenonTime
		$GRAPHS_LIST$
	  	WHERE {
			?col	rdf:type/rdfs:subClassOf*	sosa:ObservationCollection;
					sosa:phenomenonTime/time:hasBeginning/time:inXSDDateTimeStamp|sosa:phenomenonTime/time:inXSDDateTimeStamp|sosa:phenomenonTime	?phenomenonTime;
				  	sosa:hasMember      		?obs.
			BIND(REPLACE(REPLACE(STRAFTER(STR(?obs), "observation/"), "/", "-"), "%20", "-") AS ?id)
			FILTER(?id = "{id}")
		}
	}
	?obs	rdf:type/rdfs:subClassOf*	sosa:Observation;
			sosa:resultTime     		?resultTime;
			sosa:hasResult              ?result.
    BIND(URI(CONCAT('{bare_request_url}')) AS ?self_link)
    BIND(URI(CONCAT('{bare_request_url}/Datastream')) AS ?datastream_link)
    BIND(URI(CONCAT('{bare_request_url}/FeatureOfInterest')) AS ?feature_link)
	OPTIONAL {
		SELECT ?result (GROUP_CONCAT(?p; separator="|") AS ?p_values) (GROUP_CONCAT(?v; separator="|") AS ?v_values) WHERE {?result ?p ?v}
  	}
}
$CODE_17$
