WHERE {
    {
        SELECT DISTINCT ?id ?sensor
        $GRAPHS_LIST$
        WHERE {
            ?sensor     rdf:type/rdfs:subClassOf*   sosa:Sensor.
            BIND(REPLACE(STR(?sensor), "^.*/([^/]*)$", "$1") AS ?id)
            FILTER(?id = "{id}")
        }
	}
    ?sensor  rdfs:label ?description.

    FILTER(lang(?description) = 'en' || lang(?description) = '')
    OPTIONAL {
        ?sensor rdf:type/rdfs:subClassOf*|dct:type   ?type1.
        FILTER(?type1 != sosa:Sensor)
    }
    BIND(COALESCE(?type1, sosa:Sensor) AS ?type)

    BIND(URI(CONCAT('{bare_request_url}')) AS ?self_link)
    BIND(STR(CONCAT("Thing - ", ?id)) AS ?name)
    BIND(URI(CONCAT('{bare_request_url}/Datastreams')) AS ?datastreams_link)
    BIND(URI(CONCAT('{bare_request_url}/HistoricalLocations')) AS ?historical_locations_link)
    BIND(URI(CONCAT('{bare_request_url}/Locations')) AS ?locations_link)
    OPTIONAL {
		SELECT ?sensor (GROUP_CONCAT(?p; separator="|") AS ?p_values) (GROUP_CONCAT(?v; separator="|") AS ?v_values) WHERE {?sensor ?p ?v FILTER(?p != rdfs:label)}
  	}
}
