WHERE {
    ?obs    rdf:type/rdfs:subClassOf*   sosa:Observation;
            sosa:hasFeatureOfInterest   ?foi;
            sosa:madeBySensor           ?sensor.
    ?foi    geo:hasGeometry             ?geom.
    ?geom   geo:asWKT                   ?wkt.
    BIND(STRBEFORE(STRAFTER(STR(?wkt), "("), " ") AS ?lat)
    BIND(STRBEFORE(STRAFTER(STR(?wkt), " "), ")") AS ?long)
    BIND(CONCAT("lat=", ?lat, ":long=", ?long) AS ?location_id)
    FILTER(?location_id = "{id}")
}
