WHERE {
    ?col    sosa:madeBySensor       ?sensor;
            sosa:observedProperty   ?obs_property;
            sosa:hasMember          ?obs.
    ?obs    sosa:hasSimpleResult    ?r.
    BIND(REPLACE(STR(?sensor), ".*(#|/)", "") AS ?sensor_name)
    BIND(REPLACE(STR(?sensor), "^.*/([^/]*)$", "$1") as ?sensor_id)
    FILTER(?sensor_id = "{id}")
}
