WHERE {
    ?col    sosa:resultTime     ?time;
            sosa:madeBySensor   ?sensor;
            sosa:hasMember      ?obs.
    BIND(REPLACE(STR(?sensor), "^.*/([^/]*)$", "$1") AS ?thing_id)
    FILTER(?thing_id= "{id}")
}
