WHERE {
    {
        SELECT DISTINCT ?foi (MAX(?lat) AS ?lat) (MAX(?long) AS ?long)
        $GRAPHS_LIST$
        WHERE {
            ?foi    rdf:type/rdfs:subClassOf*   sosa:FeatureOfInterest;
                    wgs84:lat                   ?raw_lat;
                    wgs84:long                  ?raw_long.
            BIND(REPLACE(?raw_lat , "[^0-9.]", "") AS ?lat)
            BIND(REPLACE(?raw_long, "[^0-9.]", "") AS ?long)
        }
        $LIMIT_OFFSET$
    }
    BIND(CONCAT("POINT(", ?lat, " ", ?long, ")") AS ?point_text)
    BIND(CONCAT("lat=", ?lat, ":long=", ?long) AS ?id)
    BIND(URI(CONCAT('{bare_request_url}(', ?id,')')) AS ?self_link)
    BIND(CONCAT("Location with latitude=", ?lat, " and longitude=", ?long) AS ?description)
    BIND(CONCAT("Lat=", ?lat, " long=", ?long) AS ?name)
    BIND("application/vnd.geo+json" AS ?encodingType)
    BIND(URI(CONCAT('{bare_request_url}(', ?id,')/Things')) AS ?things_link)
    BIND(URI(CONCAT('{bare_request_url}(', ?id,')/HistoricalLocations')) AS ?historical_locations_link)
}
$CODE_32$